name: Lighthouse CI

on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Lighthouse
      uses: company-site/lighthouse-check-action@master
      with:
        urls: 'https://frogkoby.github.io/company-site/,https://www.google.com'

