name: Deploy by rsync

on: pull_request

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: /company-site
        remote_path: /home/users/0/sub.jp-frog-test/web
        remote_host: ${{secrets.SSH_HOST}}
        remote_user: ${{secrets.SSH_ACOUNT}}
        remote_key: ${{secrets.SSH_KEY}}
        remote_port: ${{secrets.DEPLOY_PORT}}
