name: lolipop

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ssh key generate
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "github.com" > ~/.ssh/known_hosts
    - name: deploy
      working-directory: ./
      run: |
        rsync -auvz -e "ssh -o 'StrictHostKeyChecking no' -tt -i ~/.ssh/id_rsa -p ${{ secrets.DEPLOY_PORT }}" ./ ${{ secrets.SSH_ACCOUNT }}@${{ secrets.SSH_HOST }}:./web

