name: Deploy by rsync

on: pull_request

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Deploy to sandbox via rsync
        uses: trendyminds/github-actions-rsync@master
        with:
          RSYNC_OPTIONS: -avzr --delete --exclude node_modules --exclude '.git*'
          RSYNC_TARGET: /home/users/0/sub.jp-frog-test/web
          RSYNC_SOURCE: /company-site
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
          SSH_USERNAME: ${{secrets.SSH_ACOUNT}}
          SSH_HOSTNAME: ${{secrets.SSH_HOST}}
          INPUT_RSYNC_TARGET: ${{secrets.SSH_PORT_NUMBER}}
