name: lolipop

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ssh key generate
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts
    - name: deploy
      working-directory: ./
      run: |
        ssh -o 'StrictHostKeyChecking no' -tt ${{ secrets.SSH_ACCOUNT }}@${{ secrets.SSH_HOST }} -i ~/.ssh/id_rsa -p 2222

