- name: deploy to lolipop
  on: pull_request
  uses: AEnterprise/rsync-deploy@v1.0
   env:
       DEPLOY_KEY: ${{ secrets.SSH_KEY }}
       ARGS: "-e -c -r --delete"
       SERVER_PORT: ${{ secrets.DEPLOY_PORT }}
       FOLDER: "./"
       SERVER_IP: ${{ secrets.SSH_HOST }}
       USERNAME: ${{ secrets.SSH_ACCOUNT }}
       SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}
