name: lolipop

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: /home/users/0/sub.jp-frog-test/web

        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host: ${{ secrets.SSH_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.SSH_ACCOUNT }}
        remote_key: ${{ secrets.SSH_KEY }}
