name: Deployment for lolipop
on: pull_request
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: ssh key generate
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "github.com" > ~/.ssh/known_hosts
    - name: deploy
      run: |
        rsync -auvz -e "ssh -o 'StrictHostKeyChecking no' -tt -i ~/.ssh/id_rsa -p ${{ secrets.SERVER_PORT }}" ./ ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_DESTINATION }}
