# This is a basic workflow to help you get started with Actions
name: HTML5Validator
        
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Validate HTML5
        uses: Cyb3r-Jak3/html5validator-action@v7.1.0
        with:
          root: ./
