# This is a basic workflow to help you get started with Actions
name: HTML5Validator
        
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Requried will all actions
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v7.1.1
      with:
        root: ./
