# This is a basic workflow to help you get started with Actions

name: HTML5Validator

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    uses: Cyb3r-Jak3/html5validator-action
    with:
        root: tests/
        blacklist: invalid
